name: smoothiejs
description: Smoothie.js wrapper for Dart

environment:
  sdk: ^2.12.0

dependencies:
  js: ^0.6.3

dev_dependencies:
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1
  lints: ^1.0.1
