name: smoothiejs
description: Smoothie.js wrapper for Dart
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: ^2.0.0

dependencies:
  js: ^0.6.1+1

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
